name: Auto Update JSON Data

on:
  schedule:
    # Mengatur jadwal berjalan otomatis setiap 6 jam sekali (bisa diubah sesuai kebutuhan)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Memungkinkan Anda menekan tombol 'Run workflow' secara manual di tab Actions GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wajib agar Actions bisa melakukan push/commit ke repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Update Script
        run: python scraping-service/update_data.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated update dynamic JSON data [skip ci]"
          branch: main
          file_pattern: scraping-service/data.json